export const Events: any = [{
    "facilitiesInfo": [{
        "id": "490bdced-aa59-44dd-8de2-29f9b4fb5791",
        "name": "Yoshinoya Japan",
        "geoX": null,
        "geoY": null,
        "imgType": null,
        "image": null,
        "address": {
            "address1": "Chuo, Sapporo, Hokkaido, Japan",
            "address2": "",
            "street": "",
            "city": "",
            "state": "",
            "country": "",
            "pinCode": null,
            "latitude": 34.061761,
            "longitude": 139.570313
        },
        "client": {
            "id": "2f975425-2428-475b-9b27-cc8db38e819f",
            "name": "Yoshinoya"
        },
        "installDate": null,
        "currentStatus": 1,
        "lastUpdatedBy": null,
        "lastUpdated": null,
        "EventActivitysInfo": [{
            "id": "e25e05c6-9757-4335-b51b-552ec24c79fd",
            "sensorId": null,
            "sensorEventId": null,
            "count": null,
            "userId": null,
            "activity": "In Progress",
            "notes": "text_update111",
            "lastUpdated": "Fri Jan 12 12:07:44 IST 2018",
            "counter": null,
            "sensor": {
                "id": "28a9fc9b-20b3-422b-9605-bfe5eb0a23ab",
                "type": "1",
                "sensorIp": null,
                "unitId": null,
                "routerId": null,
                "gatewayId": null,
                "zoneId": null,
                "originX": null,
                "originY": null,
                "installDate": null,
                "currentStatus": null,
                "lastUpdatedBy": null,
                "lastUpdated": "Fri Jan 12 12:07:44 IST 2018"
            }
        },
        {
            "id": "e25e05c6-9757-4335-b51b-552ec24c79fd",
            "sensorId": null,
            "sensorEventId": null,
            "count": null,
            "userId": null,
            "activity": "Closed",
            "notes": "text_update111",
            "lastUpdated": "Fri Jan 12 12:07:44 IST 2018",
            "counter": null,
            "sensor": {
                "id": "28a9fc9b-20b3-422b-9605-bfe5eb0a23ab",
                "type": "1",
                "sensorIp": null,
                "unitId": null,
                "routerId": null,
                "gatewayId": null,
                "zoneId": null,
                "originX": null,
                "originY": null,
                "installDate": null,
                "currentStatus": null,
                "lastUpdatedBy": null,
                "lastUpdated": "Fri Jan 12 12:07:44 IST 2018"
            }
        },
        {
            "id": "e25e05c6-9757-4335-b51b-552ec24c79fd",
            "sensorId": null,
            "sensorEventId": null,
            "count": null,
            "userId": null,
            "activity": "UnAssigned",
            "notes": "text_update111",
            "lastUpdated": "Fri Jan 12 12:07:44 IST 2018",
            "counter": null,
            "sensor": {
                "id": "28a9fc9b-20b3-422b-9605-bfe5eb0a23ab",
                "type": "1",
                "sensorIp": null,
                "unitId": null,
                "routerId": null,
                "gatewayId": null,
                "zoneId": null,
                "originX": null,
                "originY": null,
                "installDate": null,
                "currentStatus": null,
                "lastUpdatedBy": null,
                "lastUpdated": "Fri Jan 12 12:07:44 IST 2018"
            }
        }]
    },
    {
        "id": "490bdced-aa59-44dd-8de2-29f9b4fb5791",
        "name": "Tokyo Japan",
        "geoX": null,
        "geoY": null,
        "imgType": null,
        "image": null,
        "address": {
            "address1": "Chuo, Sapporo, Hokkaido, Japan",
            "address2": "",
            "street": "",
            "city": "",
            "state": "",
            "country": "",
            "pinCode": null,
            "latitude": 32.296420,
            "longitude": 133.242188
        },
        "client": {
            "id": "2f975425-2428-475b-9b27-cc8db38e819f",
            "name": "Yoshinoya"
        },
        "installDate": null,
        "currentStatus": 1,
        "lastUpdatedBy": null,
        "lastUpdated": null,
        "EventActivitysInfo": [{
            "id": "e25e05c6-9757-4335-b51b-552ec24c79fd",
            "sensorId": null,
            "sensorEventId": null,
            "count": null,
            "userId": null,
            "activity": "In Progress",
            "notes": "text_update111",
            "lastUpdated": "Fri Jan 12 12:07:44 IST 2018",
            "counter": null,
            "sensor": {
                "id": "28a9fc9b-20b3-422b-9605-bfe5eb0a23ab",
                "type": "1",
                "sensorIp": null,
                "unitId": null,
                "routerId": null,
                "gatewayId": null,
                "zoneId": null,
                "originX": null,
                "originY": null,
                "installDate": null,
                "currentStatus": null,
                "lastUpdatedBy": null,
                "lastUpdated": "Fri Jan 12 12:07:44 IST 2018"
            }
        },
        {
            "id": "e25e05c6-9757-4335-b51b-552ec24c79fd",
            "sensorId": null,
            "sensorEventId": null,
            "count": null,
            "userId": null,
            "activity": "Closed",
            "notes": "text_update111",
            "lastUpdated": "Fri Jan 12 12:07:44 IST 2018",
            "counter": null,
            "sensor": {
                "id": "28a9fc9b-20b3-422b-9605-bfe5eb0a23ab",
                "type": "1",
                "sensorIp": null,
                "unitId": null,
                "routerId": null,
                "gatewayId": null,
                "zoneId": null,
                "originX": null,
                "originY": null,
                "installDate": null,
                "currentStatus": null,
                "lastUpdatedBy": null,
                "lastUpdated": "Fri Jan 12 12:07:44 IST 2018"
            }
        },
        {
            "id": "e25e05c6-9757-4335-b51b-552ec24c79fd",
            "sensorId": null,
            "sensorEventId": null,
            "count": null,
            "userId": null,
            "activity": "In Progress",
            "notes": "text_update111",
            "lastUpdated": "Fri Jan 12 12:07:44 IST 2018",
            "counter": null,
            "sensor": {
                "id": "28a9fc9b-20b3-422b-9605-bfe5eb0a23ab",
                "type": "3",
                "sensorIp": null,
                "unitId": null,
                "routerId": null,
                "gatewayId": null,
                "zoneId": null,
                "originX": null,
                "originY": null,
                "installDate": null,
                "currentStatus": null,
                "lastUpdatedBy": null,
                "lastUpdated": "Fri Jan 12 12:07:44 IST 2018"
            }
        }]
    }, {
        "id": "490bdced-aa59-44dd-8de2-29f9b4fb5791",
        "name": "Nestle Japan",
        "geoX": null,
        "geoY": null,
        "imgType": null,
        "image": null,
        "address": {
            "address1": "Chuo, Sapporo, Hokkaido, Japan",
            "address2": "",
            "street": "",
            "city": "",
            "state": "",
            "country": "",
            "pinCode": null,
            "latitude": 42.073762,
            "longitude": 143.789063
        },
        "client": {
            "id": "2f975425-2428-475b-9b27-cc8db38e819f",
            "name": "Yoshinoya"
        },
        "installDate": null,
        "currentStatus": 1,
        "lastUpdatedBy": null,
        "lastUpdated": null,
        "EventActivitysInfo": [{
            "id": "e25e05c6-9757-4335-b51b-552ec24c79fd",
            "sensorId": null,
            "sensorEventId": null,
            "count": null,
            "userId": null,
            "activity": "In Progress",
            "notes": "text_update111",
            "lastUpdated": "Fri Jan 12 12:07:44 IST 2018",
            "counter": null,
            "sensor": {
                "id": "28a9fc9b-20b3-422b-9605-bfe5eb0a23ab",
                "type": "2",
                "sensorIp": null,
                "unitId": null,
                "routerId": null,
                "gatewayId": null,
                "zoneId": null,
                "originX": null,
                "originY": null,
                "installDate": null,
                "currentStatus": null,
                "lastUpdatedBy": null,
                "lastUpdated": "Fri Jan 12 12:07:44 IST 2018"
            }
        },
        {
            "id": "e25e05c6-9757-4335-b51b-552ec24c79fd",
            "sensorId": null,
            "sensorEventId": null,
            "count": null,
            "userId": null,
            "activity": "Action Required",
            "notes": "text_update111",
            "lastUpdated": "Fri Jan 12 12:07:44 IST 2018",
            "counter": null,
            "sensor": {
                "id": "28a9fc9b-20b3-422b-9605-bfe5eb0a23ab",
                "type": "1",
                "sensorIp": null,
                "unitId": null,
                "routerId": null,
                "gatewayId": null,
                "zoneId": null,
                "originX": null,
                "originY": null,
                "installDate": null,
                "currentStatus": null,
                "lastUpdatedBy": null,
                "lastUpdated": "Fri Jan 12 12:07:44 IST 2018"
            }
        },
        {
            "id": "e25e05c6-9757-4335-b51b-552ec24c79fd",
            "sensorId": null,
            "sensorEventId": null,
            "count": null,
            "userId": null,
            "activity": "Action Required",
            "notes": "text_update111",
            "lastUpdated": "Fri Jan 12 12:07:44 IST 2018",
            "counter": null,
            "sensor": {
                "id": "28a9fc9b-20b3-422b-9605-bfe5eb0a23ab",
                "type": "2",
                "sensorIp": null,
                "unitId": null,
                "routerId": null,
                "gatewayId": null,
                "zoneId": null,
                "originX": null,
                "originY": null,
                "installDate": null,
                "currentStatus": null,
                "lastUpdatedBy": null,
                "lastUpdated": "Fri Jan 12 12:07:44 IST 2018"
            }
        }]
    },{
        "id": "490bdced-aa59-44dd-8de2-29f9b4fb5791",
        "name": "Yoshinoya Japan",
        "geoX": null,
        "geoY": null,
        "imgType": null,
        "image": null,
        "address": {
            "address1": "Chuo, Sapporo, Hokkaido, Japan",
            "address2": "",
            "street": "",
            "city": "",
            "state": "",
            "country": "",
            "pinCode": null,
            "latitude": 33.477272,
            "longitude": 137.812500
        },
        "client": {
            "id": "2f975425-2428-475b-9b27-cc8db38e819f",
            "name": "Yoshinoya"
        },
        "installDate": null,
        "currentStatus": 1,
        "lastUpdatedBy": null,
        "lastUpdated": null,
        "EventActivitysInfo": []
    }]


}]